# -*- coding: utf-8 -*-
"""PSNR_SSIM.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dDH5HCa2M6B_kG1wNhY6p_itQbh5h9BT
"""

import numpy as np
import cv2
from skimage.metrics import structural_similarity as ssim
from skimage import io
from math import log10, sqrt
from PIL import Image

def PSNR(original,distored):

    original = original.resize(original.size)
    distored = distored.resize(original.size)

    mse_result = np.mean((original - distored) ** 2)
    max_pixel = 255.0
    psnr_result = 20 * log10(max_pixel / sqrt(mse_result))
    return psnr_result

def SSIM(original,distored):

    original = original.resize(original.size)
    distored = distored.resize(original.size)

    original_gray = cv2.cvtColor(base_image, cv2.COLOR_BGR2GRAY)
    distored_gray = cv2.cvtColor(dist_image, cv2.COLOR_BGR2GRAY)

    score_result, diff = ssim(original_gray, distored_gray, full=True)
    diff_result = (diff * 255).astype("uint8")

    return score_result

if __name__ == "__main__":
    original = Image.open('origin/000000_0_0_0_0_0.jpg')
    distored = Image.open('Distortion/2.Shoulder_50_down/000000_0_-50_0_0_0.jpg')
    PSNR_score = PSNR(original,distored)
    print('PSNR Score : %s'%PSNR_score)

    origin = cv2.imread('origin/000000_0_0_0_0_0.jpg')
    distored = cv2.imread('Distortion/2.Shoulder_50_down/000000_0_-50_0_0_0.jpg')
    SSIM_score = SSIM(origin,distored)
    print('SSIM_score : %s'%SSIM_score)